server:
  port: 8001
spring:
  datasource:
    username: mysql #输入数据库用户名
    password: 12345qwert #数据库密码
    url: jdbc:mysql://cdb-lrss4wuc.cd.tencentcdb.com:10110/collegeserver?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
  thymeleaf:
    mode: HTML5
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/*.xml
